services:
  database:
    image: 'postgres:17.4'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=bookkeeping'
      - 'POSTGRES_PASSWORD=user'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bookkeeping"]
      interval: 5s
      timeout: 5s
      retries: 5